import puppeteer from 'puppeteer-core';
const browser = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome-stable', headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1920, height: 1080 });
await page.goto('http://localhost:4321/research/', { waitUntil: 'networkidle0' });
await page.screenshot({ path: '/tmp/hero-now.png' });
await page.evaluate(() => document.getElementById('teaching').scrollIntoView({ behavior: 'instant' }));
await new Promise(r => setTimeout(r, 300));
await page.screenshot({ path: '/tmp/teach-now.png' });
await browser.close();
